# Generated by Django 5.0.6 on 2024-06-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
